[project]
name = "insighthub-worker-query"
version = "0.1.0"
description = ""
authors = [
    {name = "Nate Stott",email = "nate.stott@pm.me"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "insighthub-shared @ file:///home/nate/projects/insighthub/packages/shared/python"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
